# Generated by Django 4.1 on 2022-10-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_authorsubscribers_author_subscribers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='AuthorSubscribers',
        ),
    ]
